name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' # Or a version appropriate for the project

    - name: Vet
      run: go vet ./...

    - name: Fmt
      run: |
        gofmt -l .
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          exit 1
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
